overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-xlsbr.yml
targets:
  - README.rst: custom_readme.rst.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "setup.py": "custom_setup.py.jj2"
